#
# For licensing see accompanying LICENSE file.
# Copyright (C) 2025 Apple Inc. All Rights Reserved.
#

"""
An abstract base class for an agent that acts according to a set of preferences.
"""
import typing as t
from abc import ABC, abstractmethod
from types import SimpleNamespace

from preference_inferrer.preference_sets import PreferenceSet
from preference_inferrer.tasks.task_instances import TaskInstance
from preference_inferrer.tasks.trajectory_logger import Trajectory


class PreferenceConditionedAgent(ABC):
    """
    An abstract base class for an agent that acts based on a set of preferences.
    """
    def __init__(self, config: SimpleNamespace):
        """
        Args:
            config: configurations
        """
        self.config = config

    @abstractmethod
    def get_true_preferences(self, task_instance: TaskInstance) -> PreferenceSet:
        """
        Get the true (i.e. user's) preferences.
        Args:
            task_instance: Task to solve. Specifies the task context which determines preferences
        Returns:
            The user's true preferences as a preference set object
        """

    @abstractmethod
    def solve_task(self, task_instance: TaskInstance,
                   preferences: t.Optional[PreferenceSet] = None,
                   in_context_examples: t.Optional[t.List[str]] = None) -> Trajectory:
        """
        Create a trajectory for the current task instance using the given set of preferences.
        Args:
            task_instance: Task to solve with the provided preferences.
            preferences (Optional): Preferences to use when solving the task instance
            in_context_examples (Optional): In context examples to use when solving the task instance
        Returns:
            Trajectory of agent in the environment
        """

    def solve_task_as_user(self, task_instance: TaskInstance) -> Trajectory:
        """
        Solve the provided task_instance as the user (i.e. using the user's preferences)
        Args:
            task_instance: Task to solve.

        Returns:
            The trajectory generated by the user
        """
        user_preferences = self.get_true_preferences(task_instance)
        return self.solve_task(task_instance, is_user=True, preferences=user_preferences)

    @staticmethod
    def get_metrics() -> t.Dict:
        """
        Returns a dictionary of metrics. Base class (default) behavior is retuning an empty dictionary
        Returns:
            A dictionary of metrics
        """
        return {}
